### ISSUE TITLE
Support for async/await actions

### ISSUE THREAD

**Issue by wimason** [RokitSalad/Helpful.CircuitBreaker#6]
Hi,

I have a  async Task Foo() method that I want to call from the synchronous CircuitBreaker.Execute method. So far all I try the following unttest code fragment (only works with .NET 4.5.1, http://stackoverflow.com/questions/9343594/how-to-call-asynchronous-method-from-synchronous-method-in-c):

private async Task Foo()
        {
            throw _thrownException;
        }

        protected async override void When()
        {
            try
            {
                _circuitBreaker.Execute(() => { Task t = this.Foo(); t.GetAwaiter().GetResult(); });
            }
            catch (Exception e)
            {
                _caughtException = e;
            }
        }

The unittest will pass. Is there a better solution for this problem ? I believe it would be even better to have a ExecuteAsync method.

**Comment by RokitSalad** [comment]
Not a bad idea - I'm not 100% sold on the idea that the breaker should be aware of the context of the call it's making. Sync or async is more of a concern of the consumer - perhaps wrapping the async call in something else. 

I'll take a proper look at the problem next time I'm working on it. Perhaps if you send a pull request, the change will look more appealing.

**Comment by RokitSalad** [comment]
Async support has been added. Nuget will be updated shortly.
